packages:
  - "packages/*"
catalog:
  "browserslist": "^4.24.4"
  "browserslist-to-esbuild": "^2.1.1"
  "react": "^19.0.0"
  "react-dom": "^19.0.0"
  "@spred/core": "^0.40.2"
  "@spred/react": "^0.4.2"
  "@types/react": "^19.0.12"
  "@types/react-dom": "^19.0.4"
  "@tailwindcss/vite": "^4.1.5"
  "@vitejs/plugin-react": "^4.4.1"
  "lightningcss": "^1.29.3"
  "vite": "^6.3.5"
  "vite-css-modules": "^1.8.6"
  "vite-tsconfig-paths": "^5.1.4"
  "typed-channel": "^0.9.5"
