packages:
  - "packages/*"
catalog:
  "react": "^19.0.0"
  "react-dom": "^19.0.0"
  "@spred/core": "^0.40.2"
  "@spred/react": "^0.4.2"
  "@types/react": "^19.0.12"
  "@types/react-dom": "^19.0.4"
  "@tailwindcss/vite": "^4.0.14"
  "@vitejs/plugin-react": "^4.3.4"
  "lightningcss": "^1.29.3"
  "vite": "^6.2.2"
  "vite-css-modules": "^1.8.4"
  "vite-tsconfig-paths": "^5.1.4"
